"""Generate 3D MOL blocks for the 3Dmol.js viewers on unit-7-organic-chem.html.

Uses RDKit ETKDG embedding + MMFF94 force-field minimization (per the chemistry-toolkit
skill's smiles_to_3d.py recipe).

Output: mol3d.js exporting window.MOLECULES_3D = { name: molBlock }.
"""
from pathlib import Path
from rdkit import Chem
from rdkit.Chem import AllChem

# (key, smiles, conformers)  - more conformers for flexible chains, 1 for simple/chiral
MOLS_3D = [
    # Hydrocarbon chains - show how the zigzag is actually tetrahedral in 3D
    ('ethane',     'CC',         1),
    ('propane',    'CCC',        1),
    ('butane',     'CCCC',       5),
    ('pentane',    'CCCCC',      10),
    ('hexane',     'CCCCCC',     10),
    ('cyclohexane','C1CCCCC1',   20),  # find chair conformation

    # Stereochemistry: (R) and (S) chirality on a simple stereocenter
    # Using 2-bromobutane (textbook example)
    ('R-2-bromobutane', 'C[C@@H](Br)CC', 1),
    ('S-2-bromobutane', 'C[C@H](Br)CC',  1),
]


def smiles_to_mol_block(smiles: str, n_conformers: int = 1) -> str:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Cannot parse SMILES: {smiles!r}")
    mol = Chem.AddHs(mol)

    params = AllChem.ETKDGv3()
    params.randomSeed = 42

    if n_conformers <= 1:
        cid = AllChem.EmbedMolecule(mol, params)
        if cid < 0:
            raise RuntimeError(f"Embedding failed for {smiles}")
        AllChem.MMFFOptimizeMolecule(mol, maxIters=500)
    else:
        cids = AllChem.EmbedMultipleConfs(mol, numConfs=n_conformers, params=params)
        if not cids:
            raise RuntimeError(f"Embedding failed for {smiles}")
        # Minimize each, keep lowest-energy
        results = AllChem.MMFFOptimizeMoleculeConfs(mol, maxIters=500)
        # results = list of (converged_flag, energy) tuples
        energies = [(e, i) for i, (_, e) in enumerate(results)]
        energies.sort()
        best_cid = energies[0][1]
        # Replace conformers: keep only the best one
        best_conf = mol.GetConformer(best_cid)
        mol2 = Chem.Mol(mol)
        mol2.RemoveAllConformers()
        mol2.AddConformer(best_conf, assignId=True)
        mol = mol2

    return Chem.MolToMolBlock(mol)


def js_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")


def main():
    out_path = Path(__file__).parent / "mol3d.js"
    lines = ["/* Generated by build_3d.py - do not hand-edit. */",
             "/* 3D MOL blocks for use with 3Dmol.js. */",
             "window.MOLECULES_3D = {"]
    for key, smi, n in MOLS_3D:
        block = smiles_to_mol_block(smi, n)
        lines.append(f"  {key!r}: `{js_escape(block)}`,")
        print(f"  {key:20s} {smi:25s} ({n} conf{'s' if n>1 else ''})")
    lines.append("};")
    out_path.write_text("\n".join(lines))
    print(f"\nWrote {len(MOLS_3D)} MOL blocks to {out_path}")
    print(f"File size: {out_path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
